logo: "https://crisprintsstuff.github.io/Discord-LFG-Bot/assets/images/23.png"
title: Discord LFG Bot
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://crisprintsstuff.github.io/Discord-LFG-Bot

color_scheme: dark

aux_links:
  Download Here: #
